
x-app-env: &app-environment
  env_file:
    - .env

services:
  api:
    container_name: hope-api
    build: .
    command: uvicorn service_app:app --host 0.0.0.0 --port 8080
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    <<: *app-environment
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  worker:
    container_name: hope-worker
    build: .
    command: celery -A celery_app worker --loglevel=info
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    <<: *app-environment
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    container_name: hope-db
    image: ankane/pgvector:latest
    <<: *app-environment
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  redis:
    container_name: hope-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pg_data:

networks:
  default:
    name: hope_default
