version: "3.9"

x-app-env: &app-environment
  env_file:
    - .env

services:
  api:
    container_name: hope-api
    build: .
    command: uvicorn service_app:app --host 0.0.0.0 --port 8080
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    <<: *app-environment
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  worker:
    container_name: hope-worker
    build: .
    command: celery -A celery_app worker --loglevel=info --concurrency=3 --max-tasks-per-child=2 --prefetch-multiplier=1 --max-memory-per-child=400000 -Q ${CELERY_DEFAULT_QUEUE:-celery} -n default@%h
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    <<: *app-environment
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  worker-ocr:
    container_name: hope-worker-ocr
    build: .
    command: celery -A celery_app worker --loglevel=info --concurrency=2 --max-tasks-per-child=2 --prefetch-multiplier=1 --max-memory-per-child=400000 -Q ${CELERY_OCR_QUEUE:-ocr} -n ocr@%h
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    <<: *app-environment
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    container_name: hope-db
    image: ankane/pgvector:latest
    <<: *app-environment
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  redis:
    container_name: hope-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

  flower:
    container_name: hope-flower
    build: .
    command: celery -A celery_app flower --address=0.0.0.0 --port=5555 --basic_auth=admin:anko2025
    <<: *app-environment
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
    ports:
      - "5555:5555"

  celery-exporter:
    container_name: hope-celery-exporter
    image: danihodovic/celery-exporter:latest
    command: ["--broker-url=${CELERY_BROKER_URL}"]
    <<: *app-environment
    depends_on:
      - redis
      - worker
    ports:
      - "9808:9808"

  prometheus:
    container_name: hope-prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/web.yml:/etc/prometheus/web.yml:ro
      - prom_data:/prometheus
    depends_on:
      - celery-exporter
    ports:
      - "9090:9090"

volumes:
  pg_data:
  prom_data:

networks:
  default:
    name: hope_default
